### ISSUE TITLE
Error with "Find Free TMT IDs Within a Range"

### ISSUE THREAD

**Issue by scroberts** [TMTSystemsEngineering/DXL-Library-Files#15]
I ran this script in the OAD and it seems to be identifying an ID as free that is used (REQ-1-OAD-9901). 

Module: OAD
ID1 = 9900
ID2 = 9950
Looping over objects... 
These IDs are unused within that range:
9901
9903
9905
9907
9909
9911
9913
9915
9917
9919
9921
9923
9925
9927
9929
9931
9933
9935
9937
9939
9941
9943
9945
9947
9949
There are 25 unused IDs in that range.
Finished

**Comment by kayhardie** [comment]
@michaelevans1111, any ideas? I get the same results as Scott but can't figure out why. I thought maybe the TMT ID field wasn't correctly populated but it looks fine, so I looked over the code but nothing stands out.

**Comment by michaelevans1111** [comment]
Interesting.  Lemme take a look.  I have one idea, but it's a long shot.

**Comment by michaelevans1111** [comment]
OK, my first idea failed.  Now I have another idea.  This time I'll look at the code.

**Comment by michaelevans1111** [comment]
Try it again!  I think I fixed it.
I found an extra space character at the end of the string in the TMT ID field.  I deleted it.

**Comment by kayhardie** [comment]
Yup, that worked! Is there a reason why the script is picking up that last space, or can it be modified to avoid “counting" it? I’m concerned this might happen a lot since it’s an extra space is not the most obvious thing to notice.

**Comment by michaelevans1111** [comment]
the code can certainly be changed
i wrote it to be fast and simple
and choosing to not trap stupid user errors like this
so there’s plenty that can trip it up
this one simply takes the last 4 characters of the TMT ID field

you can go ahead and modify it to use some regexp and trim off any whitespace characters at the end
or look for only digits

**Comment by kayhardie** [comment]
Ok thanks, I’ll take a look!

**Comment by scroberts** [comment]
Thanks all,

Yes, the data should be stripped of left / right white spaces before processing in the script.   I found this snippet on the web that could do that.

string rightTrim(string s) {
    if (null(s)) return "";
    int first = 0;
    int last = length(s) - 1;
    while( (last > -1) && (isspace(s[last])) ){
       last--;
    }
    return(s[first:last]);
}
 
string leftTrim(string s) {
    if (null(s)) return "";
    int first = 0;
    int last = length(s) - 1;
    while( (isspace(s[first])) && (first < last) ) {
       first++;
    }
    return(s[first:last]);
}
 
 
string trim(string s) {
    return(leftTrim(rightTrim(s)));
}


Scott

**Comment by michaelevans1111** [comment]
I am closing this issue, since we fixed it.
